spring:
  application:
    name: itoken-config
  zipkin:
    base-url: http://localhost:9411
  cloud:
    config:
      label: master
      server:
        git:
          uri: http://192.168.137.128/itoken/itoken-config.git
          search-paths: respo
          username: root
          password: 12345678

  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8888

eureka:
  client:
    serviceURL:
      defaultZone: http://192.168.137.131:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
