spring:
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411
  application:
    name: itoken-zuul

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: itoken-ribbon
    api-b:
      path: /api/b/**
      serviceId: itoken-feign